# ==============================================================================
# ФАЙЛ: gradle.properties
# ВЕРСИЯ: 1.0.0
# ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ: 2026-09-04 04:28:00 (UTC+4, Ижевск)
# 
# ИСТОРИЯ ИЗМЕНЕНИЙ (CHANGELOG):
# ------------------------------------------------------------------------------
# 2026-09-04 04:28 | v1.0.0 | Включен android.useAndroidX и параметры JVM для сборки
# ==============================================================================

android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
